server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: joshua625

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
